### ISSUE TITLE
Checkout Page

### ISSUE THREAD

**Issue by roshan-ponnachen02** [RohitKV1n0d/orange_cat_web#148]
### Description:
- **Functionality: Design and implement a secure and user-friendly checkout process.**

### Tasks:
- [ ] **Design Checkout Page:**
  - **Create wireframes or mockups for the checkout page layout.**
  - **Include fields for entering shipping address, billing information, payment method selection, order summary, etc.**
- [ ] **Implement Checkout Form:**
  - **Develop HTML/CSS forms for capturing user input during checkout.**
  - **Ensure the form is responsive and accessible across different devices.**
- [ ] **Integrate Payment Gateway (Stripe):**
  - **Implement Stripe API for secure payment processing.**
  - **Verify that payment information is encrypted and transmitted securely.**
- [ ] **Error Handling and Validation:**
  - **Validate user input in the checkout form fields (e.g., email format, required fields).**
  - **Display meaningful error messages for incorrect or missing information.**
- [ ] **Order Summary Display:**
  - **Dynamically generate and display an order summary based on the selected products and quantities.**
  - **Ensure that the order total, including taxes and shipping costs, is calculated accurately.**

### Test Cases:
- [ ] **Checkout Form Fields Validation:**
  - **Test that validation rules are applied to all required fields in the checkout form.**
  - **Verify that appropriate error messages are displayed for invalid inputs.**
- [ ] **Payment Processing:**
  - **Test the integration with Stripe payment gateway.**
  - **Verify that payments are processed securely and successfully.**
- [ ] **Order Summary Accuracy:**
  - **Test that the order summary displays all selected products and quantities accurately.**
  - **Verify that the total amount reflects the correct prices, taxes, and shipping costs.**

### Figma Screenshots:
- ![image](https://github.com/RohitKV1n0d/orange_cat_web/assets/168718965/05776f35-f2d2-45b1-9c1d-63508c39d061)

- ![image](https://github.com/RohitKV1n0d/orange_cat_web/assets/168718965/972ed8ae-6266-4728-bf37-6fa1dee1b5d6)

- ![image](https://github.com/RohitKV1n0d/orange_cat_web/assets/168718965/4b30fd75-6bc6-4439-9bb9-ac4bba430089)

## Rationale:
**Designing a user-friendly and secure checkout process is crucial for providing a seamless shopping experience and ensuring customer trust and satisfaction.**

## Proposed Solution:
**Design and implement a checkout page that guides users through the payment process smoothly, integrates with Stripe for secure payments, and provides clear feedback on order details and validation errors.**

## Additional Context:
**Coordinate with backend developers to ensure integration with the database for order management and processing.**

## Impact:
**A well-designed checkout page is expected to reduce cart abandonment rates, increase conversion rates, and enhance overall customer satisfaction with the e-commerce platform.**

**Comment by RohitKV1n0d** [comment]
## Checkout page Redesign 
- <img width="879" alt="Screenshot 2024-05-08 at 12 23 17 PM" src="https://github.com/RohitKV1n0d/orange_cat_web/assets/44728349/9b53ddfe-e27c-4e50-b96e-8cd19eb40c53">
- @swathikrishnaus please revice the code to match this design

**Comment by roshan-ponnachen02** [comment]
@RohitKV1n0d 

## Page Issue 

## Environment

https://orangecatcycles.com/checkout/1

## Description
After proceed for payment from checkout ,the page is not moving forward to next page.


https://github.com/RohitKV1n0d/orange_cat_web/assets/168718965/555f2267-575e-4045-a038-6ebc294dbd91

**Comment by RohitKV1n0d** [comment]
Fixed with #151

**Comment by roshan-ponnachen02** [comment]
@RohitKV1n0d ## Found issue while confirm payment 

## Description 

- In the Checkout page,

- Showing error While click on pay.

https://github.com/RohitKV1n0d/orange_cat_web/assets/168718965/a1cc6519-bc72-453f-b081-058d8b5f9a54
