### ISSUE TITLE
Update Product Details Page Layout and Content

### ISSUE THREAD

**Issue by RohitKV1n0d** [RohitKV1n0d/orange_cat_web#59]
## Issue Title
Update Product Details Page Layout and Content

## Description
This issue outlines the necessary changes to be made on the product details page. The current layout displaying cost and variants information will be replaced with a product description. Additionally, the section below the product images will now include technical details about the bike.

## Tasks Checklist
- [x] **Remove Cost and Variants Information**:
  - Identify and remove existing elements related to cost and product variants from the product details page.

- [x] **Add Product Description**:
  - Replace the removed sections with a detailed product description.
  - Ensure the description is clear, informative, and aligns with branding guidelines.

- [x] **Technical Details Section**:
  - Create a new section below the product images.
  - This section should include comprehensive technical details about the bike.
  - Layout and design this section for easy readability and aesthetic alignment with the rest of the page.

- [x] **Add Enquire now Modal**:
  - Modal to collect contact info and product in interest to be open when ENQUIR btn is clicked

- [x] **Design Updates**:
  - Incorporate new design elements and images as provided.
  - Ensure that these updates are responsive and consistent with the overall website design.

- [x] **Testing**:
  - Test the updated page for functionality, responsiveness, and compatibility across different browsers and devices.
  - Ensure that all new content is displayed correctly and without errors.

- [x] **Review and Feedback**:
  - Share the updated page with relevant stakeholders for feedback.
  - Implement any feedback or revisions as necessary.

## Additional Information
- <img width="1304" alt="image" src="https://github.com/RohitKV1n0d/orange_cat_web/assets/44728349/70ad928a-1a1b-493c-840c-61dd209d3d29">
- Please find the new changes in the figma https://www.figma.com/file/14c7iDisXF34wycyLuZMQv/Orange-Cats?type=design&node-id=0-1&mode=design&t=0qPD1eSiO3Czkhuo-0D
- <img width="851" alt="image" src="https://github.com/RohitKV1n0d/orange_cat_web/assets/44728349/b32b3fae-bda7-4888-894b-78d71c5011e3">
- <img width="815" alt="image" src="https://github.com/RohitKV1n0d/orange_cat_web/assets/44728349/cb097027-cfb7-4155-b18f-84b6798da566">
