### ISSUE TITLE
Relocate Quote to Homepage S-Subscribe Section with Styling Updates

### ISSUE THREAD

**Issue by RohitKV1n0d** [RohitKV1n0d/orange_cat_web#68]
# Relocate Quote to Homepage S-Subscribe Section with Styling Updates

## Description
This issue involves relocating the quote “A bicycle is not just a combination of details. Its details are everything.” from the About Us page to the S-Subscribe section of the homepage. The text in the S-Subscribe section should be replaced with this quote, and the font size and style should be updated to make it more prominent and visually appealing.

## Tasks Checklist
- [x] **Relocate Quote**:
  - Remove the quote from the About Us page.
  - Insert the quote “A bicycle is not just a combination of details. Its details are everything.” into the S-Subscribe section of the homepage.

- [x] **Update Text Style**:
  - Increase the font size of the quote to enhance visibility.
  - Change the text to Italian case (use an appropriate font style that reflects Italian typography, if available).

- [x] **Design Adjustments**:
  - Ensure the new text styling aligns aesthetically with the homepage design.
  - Adjust layout and spacing if necessary to accommodate the larger font size and new style.

- [x] **Review and Feedback**:
  - Present the updated section to stakeholders for feedback.
  - Implement any revisions based on the feedback received.

- [x] **Testing**:
  - Test the updated S-Subscribe section for responsiveness and compatibility across different devices and browsers.
  - Ensure the quote is displayed correctly and is visually impactful.

- [x] **Sample Images for Inspiration**:
  - Review any sample images provided for inspiration to guide the styling and layout.

## Additional Information
- <img width="1459" alt="image" src="https://github.com/RohitKV1n0d/orange_cat_web/assets/44728349/8ab383a8-5802-489d-930f-b11b46740876">
- Add it here like this, but with different font stlye
- <img width="542" alt="image" src="https://github.com/RohitKV1n0d/orange_cat_web/assets/44728349/a3f8581a-2b98-4859-a1bb-08b0a1ecbb55">
- Something like this one above
