### ISSUE TITLE
Enhancement: Add Color Variants to Cycle Product Listings

### ISSUE THREAD

**Issue by RohitKV1n0d** [RohitKV1n0d/orange_cat_web#71]
# Enhancement: Add Color Variants to Cycle Product Listings

## Description
This issue addresses the need to update our current product listings, which feature only two cycles, to include two color variants for each cycle. This enhancement will provide more options to our customers and improve the overall shopping experience.

## Tasks Checklist
- [x] **Identify Color Variants**:
  - Determine the two color variants for each of the two cycle models currently listed.

- [ ] **Update Product Listings**:
  - Modify each cycle's product listing to include options for the two color variants.
  - Ensure each variant is represented with corresponding images and descriptions.

- [ ] **Design Changes for Displaying Variants**:
  - Implement design changes to the product listing pages to accommodate the display of color variants.
  - Design should allow customers to easily view and select from the available color options.

- [ ] **Product Images**:
  - Ensure high-quality images are available for each color variant.
  - Update the product gallery to include images of each variant.

- [ ] **Testing and Validation**:
  - Test the updated listings for functionality, ensuring that the variants are selectable and displayed correctly.
  - Check responsiveness and compatibility across various devices and browsers.

- [ ] **UI/UX Considerations**:
  - Ensure the design is user-friendly and intuitive, allowing easy navigation between different color variants.
  - Confirm that the new design aligns with the overall aesthetic of the website.

- [ ] **Stakeholder Review**:
  - Present the updated product listings to stakeholders for feedback.
  - Implement any changes based on the feedback received.

**Comment by RohitKV1n0d** [comment]
@swathikrishnaus Please let me know when you start working on this, we'll discus the design changes before implementing

**Comment by RohitKV1n0d** [comment]
Also show the color variants in homepage too

**Comment by RohitKV1n0d** [comment]
<img width="1082" alt="image" src="https://github.com/RohitKV1n0d/orange_cat_web/assets/44728349/739f5540-d582-4131-896c-f5f60a5c6549">


Show the variants here too
